# 使用官方的 Nginx 基礎映像檔
FROM nginx:alpine

# 複製您的自定義 nginx.conf 到容器的正確位置
# 假設您的 nginx.conf 檔案在與此 Dockerfile 相同的目錄下 (即 ./nginx-docker/nginx.conf)
COPY nginx-docker/nginx.conf /etc/nginx/conf.d/default.conf

#這裡的路徑是相對於 docker-compose.yml 的位置。
COPY frontend/build /usr/share/nginx/html

# 暴露 Nginx 監聽的 80 埠
EXPOSE 80

RUN chown -R root:root /usr/share/nginx/html && chmod -R 755 /usr/share/nginx/html

# 啟動 Nginx 並使其保持在前台運行
CMD ["nginx", "-g", "daemon off;"]

#http://192.168.50.168:3000