# Generated by Django 5.2 on 2025-05-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmanage', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
