# Generated by Django 5.2.3 on 2025-06-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmanage', '0003_borrowrecord_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('SCIENCE', '科學'), ('LANGUAGE', '語言'), ('HISTORY', '歷史'), ('FICTION', '小說'), ('ENGINEERING', '工程'), ('ART', '藝術'), ('COMPUTER', '電腦'), ('OTHER', '其他')], default='OTHER', max_length=50, verbose_name='書籍分類'),
        ),
    ]
