# Generated by Django 5.2.3 on 2025-06-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmanage', '0004_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', '可借閱'), ('DAMAGED', '已損壞'), ('UNDER_REPAIR', '維修中'), ('LOST', '遺失')], default='AVAILABLE', max_length=20, verbose_name='書籍狀態'),
        ),
    ]
